### ISSUE TITLE
document inference

### ISSUE THREAD

**Issue by geovedi** [cemoody/lda2vec#12]
hi, 

could you provide example for predicting new document topics or vectors from trained model?

thanks.

**Comment by tokestermw** [comment]
My guess is you would use something like `fit_partial` here: https://github.com/cemoody/lda2vec/blob/master/examples/twenty_newsgroups/lda2vec/lda2vec_model.py#L37

There is an `update_only_docs` option that freezes the word embedding matrix and topic matrix.

Then in the mixture, you fit a new `w` for the new document and replace it with the `w` here: https://github.com/cemoody/lda2vec/blob/master/lda2vec/embed_mixture.py#L108

It would be great to have this functionality in official capacity.

**Comment by yg37** [comment]
I randomly initialized a topic distribution vector for the new document and appended it to the document matrix from the training. Then I used `fit_partial` with `update_only_docs` set to True. After a few hundred epochs, I was getting decent topic distribution of the new document. The problem is that the new document vector is not as sparse as the document vectors from the training. Maybe increasing the number of epochs can solve the problem, but then it would take too long for prediction.

**Comment by grivescorbett** [comment]
@yg37 have you done any additional thinking on this?

**Comment by alexwongdl** [comment]
@yg37 "I randomly initialized a topic distribution vector for the new document and appended it to the document matrix from the training." what if only use the  topic distribution vector of the new document without the document matrix from the training?
