### ISSUE TITLE
Remove spaCy as a dependency

### ISSUE THREAD

**Issue by shirish93** [cemoody/lda2vec#2]
Hi @cemoody 

I see spaCy being used ONCE in the text (to tokenize). Might I suggest making lda2vec more language-agnostic, and removing the dependency, and leaving the onus of tokenizing upon the user? I was hoping to get started on lda2Vec, and it the spaCy requirement automatically implied English, and that made me reluctant.

**Comment by jmomarty** [comment]
+1

**Comment by cemoody** [comment]
Good point! I'll add it to my TODO list

**Comment by geovedi** [comment]
how about using `gensim.corpora` instead for preprocessing?

**Comment by cemoody** [comment]
Since this comment, I've actually come to rely more deeply on spaCy and using to provide word vectors at initialization in addition to preprocessing the text in various ways. And in the short term future, I'd like to use to build dependency trees and models off of them. As a result, I'm closing this issue and keeping the spaCy req
